[versions]
accompanist = "0.37.3"
activityCompose = "1.12.2"
androidGradlePlugin = "8.13.2"
androidxComposeBom = "2025.12.00"
appcompatResources = "1.7.1"
coreKtx = "1.16.0"
datastore-preferences = "1.2.0"
espressoCore = "3.7.0"
geohash = "1.4.0"
glide = "5.0.5"
junit = "4.13.2"
junitVersion = "1.3.0"
kotlin = "2.2.21"
ksp = "2.3.3"
lifecycleLivedataKtx = "2.9.4"
navigationCompose = "2.9.5"
room = "2.8.4"

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
ksp = {id="com.google.devtools.ksp", version.ref = "ksp"}
room = {id="androidx.room", version.ref="room"}

[libraries]

accompanist-drawablePainter = {group="com.google.accompanist", name="accompanist-drawablepainter", version.ref = "accompanist"}
accompanist-permissions = {group="com.google.accompanist", name="accompanist-permissions", version.ref = "accompanist"}
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
androidx-appcompat-resources = { module = "androidx.appcompat:appcompat-resources", version.ref = "appcompatResources" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "androidxComposeBom" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
androidx-datastore-preferences = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "datastore-preferences" }
androidx-datastore-preferences-core = { group = "androidx.datastore", name = "datastore-preferences-core", version.ref = "datastore-preferences" }
androidx-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCore" }
androidx-junit = { module = "androidx.test.ext:junit", version.ref = "junitVersion" }
androidx-lifecycle-livedata-ktx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycleLivedataKtx" }
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycleLivedataKtx" }
androidx-material-icons-extended = { module = "androidx.compose.material:material-icons-extended" }
androidx-material3 = { module = "androidx.compose.material3:material3" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigationCompose" }
androidx-room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
androidx-room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
androidx-room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
androidx-ui = { module = "androidx.compose.ui:ui" }
androidx-ui-graphics = { module = "androidx.compose.ui:ui-graphics" }
androidx-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4" }
androidx-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest" }
androidx-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
androidx-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
geohash = { module = "ch.hsr:geohash", version.ref = "geohash" }
glide = {group="com.github.bumptech.glide", name="glide", version.ref = "glide"}
glide-compose = {group="com.github.bumptech.glide", name="compose", version="1.0.0-beta08"}
glide-ksp = {group="com.github.bumptech.glide", name="ksp",  version.ref = "glide"}
junit = { module = "junit:junit", version.ref = "junit" }
